// ─────────────────────────────────────────────────────────────────────────────
// Pool d'exercices taggés — Calli Recomp
// Chaque exercice est taggé par :
//   - catégorie (push/pull/legs/core/cardio/skill)
//   - groupes musculaires ciblés
//   - équipement requis (au minimum)
//   - difficulté (1=débutant, 2=intermédiaire, 3=avancé)
// Le moteur de génération filtre ce pool selon l'équipement disponible,
// le niveau, l'objectif et le split choisi.
// ─────────────────────────────────────────────────────────────────────────────

export type ExerciseCategory = "push" | "pull" | "legs" | "core" | "cardio" | "skill";
export type EquipmentTag =
  | "bodyweight" // poids du corps
  | "pullup-bar" // barre de traction
  | "rings" // anneaux
  | "bands" // élastiques
  | "dumbbells" // haltères
  | "trx" // sangle TRX
  | "rower" // rameur
  | "pool" // piscine
  | "bike" // vélo
  | "none"; // aucun (repos, étirements)

export interface ExerciseTemplate {
  id: string;
  name: string;
  category: ExerciseCategory;
  muscleGroups: string[];
  /** Équipement minimum nécessaire — un exercice est disponible si l'utilisateur possède AU MOINS UN de ces tags */
  equipment: EquipmentTag[];
  difficulty: 1 | 2 | 3;
  kind: "reps" | "time" | "distance";
  /** Fourchette de reps ou de temps recommandée (débutant → avancé) */
  defaultSets: number;
  defaultTargetMin: number;
  defaultTargetMax: number;
  defaultRest: number; // secondes
  progression: string;
  /** IDs d'exercices alternatifs (même catégorie, difficulté similaire ou régressive) */
  alternatives: string[];
}

/**
 * Un exercice est "disponible" si l'utilisateur possède au moins un des équipements
 * requis. "bodyweight" est toujours disponible (on n'a jamais besoin d'équipement
 * pour les exercices de poids du corps).
 */
export function isExerciseAvailable(ex: ExerciseTemplate, userEquipment: EquipmentTag[]): boolean {
  if (ex.equipment.length === 0 || ex.equipment.includes("none")) return true;
  return ex.equipment.some((eq) => eq === "bodyweight" || userEquipment.includes(eq));
}

/**
 * Filtre le pool d'exercices selon l'équipement disponible.
 * Garde les exercices "bodyweight" et "none" (toujours disponibles).
 */
export function filterByEquipment(
  exercises: ExerciseTemplate[],
  userEquipment: EquipmentTag[],
): ExerciseTemplate[] {
  return exercises.filter((ex) => isExerciseAvailable(ex, userEquipment));
}

/**
 * Filtre par catégorie musculaire.
 */
export function filterByCategory(
  exercises: ExerciseTemplate[],
  category: ExerciseCategory,
): ExerciseTemplate[] {
  return exercises.filter((ex) => ex.category === category);
}

/**
 * Filtre par groupe musculaire ciblé.
 */
export function filterByMuscleGroup(
  exercises: ExerciseTemplate[],
  muscle: string,
): ExerciseTemplate[] {
  return exercises.filter((ex) => ex.muscleGroups.includes(muscle));
}

/**
 * Filtre par niveau de difficulté (garde les exercices à ou en dessous du niveau).
 */
export function filterByDifficulty(
  exercises: ExerciseTemplate[],
  maxDifficulty: 1 | 2 | 3,
): ExerciseTemplate[] {
  return exercises.filter((ex) => ex.difficulty <= maxDifficulty);
}

/**
 * Sélectionne un exercice aléatoire parmi les options, en évitant les doublons.
 */
export function selectExercises(
  pool: ExerciseTemplate[],
  count: number,
  usedIds: Set<string> = new Set(),
): ExerciseTemplate[] {
  const available = pool.filter((ex) => !usedIds.has(ex.id));
  const selected: ExerciseTemplate[] = [];
  const shuffled = [...available].sort(() => Math.random() - 0.5);

  for (const ex of shuffled) {
    if (selected.length >= count) break;
    if (!usedIds.has(ex.id)) {
      selected.push(ex);
      usedIds.add(ex.id);
    }
  }
  return selected;
}

// ─────────────────────────────────────────────────────────────────────────────
// Pool complet des exercices
// ─────────────────────────────────────────────────────────────────────────────

export const EXERCISE_POOL: ExerciseTemplate[] = [
  // ── PUSH : ÉPAULES ──
  {
    id: "pike-pushup",
    name: "Pike push-up",
    category: "push",
    muscleGroups: ["épaules", "triceps"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 8,
    defaultTargetMax: 15,
    defaultRest: 60,
    progression: "Vers pike push-up lesté, puis HSPU",
    alternatives: ["pike-pushup-weighted", "hspu-negative-wall"],
  },
  {
    id: "pike-pushup-weighted",
    name: "Pike push-up lesté",
    category: "push",
    muscleGroups: ["épaules", "triceps"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 6,
    defaultTargetMax: 12,
    defaultRest: 90,
    progression: "Vers HSPU mur",
    alternatives: ["pike-pushup", "hspu-negative-wall"],
  },
  {
    id: "hspu-negative-wall",
    name: "HSPU négatif mur",
    category: "push",
    muscleGroups: ["épaules", "triceps"],
    equipment: ["bodyweight", "pullup-bar"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 3,
    defaultTargetMax: 6,
    defaultRest: 90,
    progression: "Vers HSPU au mur",
    alternatives: ["hspu-wall", "pike-pushup"],
  },
  {
    id: "hspu-wall",
    name: "HSPU au mur",
    category: "push",
    muscleGroups: ["épaules", "triceps"],
    equipment: ["bodyweight"],
    difficulty: 3,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 4,
    defaultTargetMax: 8,
    defaultRest: 120,
    progression: "Vers HSPU libre",
    alternatives: ["hspu-negative-wall", "pike-pushup-weighted"],
  },
  {
    id: "handstand-free",
    name: "Handstand libre",
    category: "skill",
    muscleGroups: ["épaules", "core"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "time",
    defaultSets: 5,
    defaultTargetMin: 5,
    defaultTargetMax: 15,
    defaultRest: 60,
    progression: "Vers handstand libre contrôlé",
    alternatives: ["handstand-wall"],
  },
  {
    id: "handstand-wall",
    name: "Handstand au mur",
    category: "skill",
    muscleGroups: ["épaules", "core"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "time",
    defaultSets: 5,
    defaultTargetMin: 15,
    defaultTargetMax: 45,
    defaultRest: 60,
    progression: "Vers handstand libre",
    alternatives: ["handstand-free", "wall-walk"],
  },

  // ── PUSH : POITRINE ──
  {
    id: "pushup-standard",
    name: "Pompes standard",
    category: "push",
    muscleGroups: ["poitrine", "épaules", "triceps"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 10,
    defaultTargetMax: 20,
    defaultRest: 60,
    progression: "Vers pompes déclinées, puis archer",
    alternatives: ["pushup-decline", "pushup-archer"],
  },
  {
    id: "pushup-decline",
    name: "Pompes déclinées",
    category: "push",
    muscleGroups: ["poitrine", "épaules", "triceps"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 8,
    defaultTargetMax: 15,
    defaultRest: 60,
    progression: "Vers pompes archer",
    alternatives: ["pushup-standard", "pushup-archer"],
  },
  {
    id: "pushup-archer",
    name: "Pompes archer",
    category: "push",
    muscleGroups: ["poitrine", "épaules", "triceps"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 6,
    defaultTargetMax: 10,
    defaultRest: 90,
    progression: "Vers pompes archer profondes",
    alternatives: ["pushup-decline", "pushup-standard"],
  },
  {
    id: "pushup-diamond",
    name: "Pompes diamant",
    category: "push",
    muscleGroups: ["triceps", "poitrine"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 6,
    defaultTargetMax: 12,
    defaultRest: 60,
    progression: "Vers dips lestés",
    alternatives: ["dips", "pushup-standard"],
  },

  // ── PUSH : TRICEPS ──
  {
    id: "dips",
    name: "Dips",
    category: "push",
    muscleGroups: ["triceps", "épaules", "poitrine"],
    equipment: ["bodyweight", "rings", "pullup-bar", "dumbbells"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 6,
    defaultTargetMax: 12,
    defaultRest: 90,
    progression: "Vers dips lestés ou profonds",
    alternatives: ["dips-chairs", "pushup-diamond"],
  },
  {
    id: "dips-chairs",
    name: "Dips entre deux chaises",
    category: "push",
    muscleGroups: ["triceps", "épaules", "poitrine"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 8,
    defaultTargetMax: 15,
    defaultRest: 60,
    progression: "Vers dips",
    alternatives: ["dips", "pushup-diamond"],
  },

  // ── PULL : DOS/TIRAGE ──
  {
    id: "pullups-strict",
    name: "Tractions strictes",
    category: "pull",
    muscleGroups: ["dos", "biceps", "avant-bras"],
    equipment: ["pullup-bar", "rings"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 5,
    defaultTargetMax: 10,
    defaultRest: 90,
    progression: "Vers chest-to-bar, puis explosives",
    alternatives: ["pullups-negative", "australian-pullups"],
  },
  {
    id: "pullups-negative",
    name: "Tractions négatives",
    category: "pull",
    muscleGroups: ["dos", "biceps", "avant-bras"],
    equipment: ["pullup-bar", "rings"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 3,
    defaultTargetMax: 6,
    defaultRest: 90,
    progression: "Vers tractions strictes",
    alternatives: ["pullups-strict", "australian-pullups"],
  },
  {
    id: "australian-pullups",
    name: "Rows inversés / Australian pull-ups",
    category: "pull",
    muscleGroups: ["dos", "biceps"],
    equipment: ["bodyweight", "pullup-bar", "rings", "bands"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 8,
    defaultTargetMax: 15,
    defaultRest: 90,
    progression: "Vers tractions ou Australian sous table",
    alternatives: ["pullups-negative", "pullups-strict"],
  },
  {
    id: "chinups-supinated",
    name: "Chin-ups / tractions supinées",
    category: "pull",
    muscleGroups: ["dos", "biceps"],
    equipment: ["pullup-bar", "rings"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 5,
    defaultTargetMax: 10,
    defaultRest: 90,
    progression: "Vers tractions supinées explosives",
    alternatives: ["pullups-strict", "chinups-negative"],
  },
  {
    id: "chest-to-bar",
    name: "Chest-to-bar",
    category: "pull",
    muscleGroups: ["dos", "biceps"],
    equipment: ["pullup-bar", "rings"],
    difficulty: 3,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 3,
    defaultTargetMax: 6,
    defaultRest: 90,
    progression: "Vers muscle-up",
    alternatives: ["pullups-explosive", "pullups-strict"],
  },
  {
    id: "pullups-explosive",
    name: "Tractions explosives",
    category: "pull",
    muscleGroups: ["dos", "biceps"],
    equipment: ["pullup-bar", "rings"],
    difficulty: 3,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 3,
    defaultTargetMax: 6,
    defaultRest: 120,
    progression: "Vers muscle-up",
    alternatives: ["chest-to-bar", "pullups-strict"],
  },
  {
    id: "muscleup-transition-band",
    name: "Transition muscle-up bande",
    category: "skill",
    muscleGroups: ["dos", "épaules", "triceps", "biceps"],
    equipment: ["pullup-bar", "bands"],
    difficulty: 3,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 3,
    defaultTargetMax: 6,
    defaultRest: 90,
    progression: "Vers muscle-up libre",
    alternatives: ["pullups-explosive", "transition-floor"],
  },
  {
    id: "transition-floor",
    name: "Transition allongé au sol",
    category: "skill",
    muscleGroups: ["dos", "épaules", "triceps", "biceps"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 5,
    defaultTargetMax: 10,
    defaultRest: 60,
    progression: "Vers muscle-up bande",
    alternatives: ["muscleup-transition-band", "pullups-explosive"],
  },

  // ── PULL : L-SIT & CORE HANGING ──
  {
    id: "leg-raises-hanging",
    name: "Relevés de jambes suspendus",
    category: "pull",
    muscleGroups: ["abdos", "obliques", "iliens"],
    equipment: ["pullup-bar", "rings"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 8,
    defaultTargetMax: 15,
    defaultRest: 60,
    progression: "Vers toes-to-bar",
    alternatives: ["knee-raises", "leg-raises-floor"],
  },
  {
    id: "knee-raises",
    name: "Relevés de genoux suspendus",
    category: "pull",
    muscleGroups: ["abdos", "obliques"],
    equipment: ["pullup-bar", "rings"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 10,
    defaultTargetMax: 15,
    defaultRest: 60,
    progression: "Vers relevés de jambes",
    alternatives: ["leg-raises-hanging", "leg-raises-floor"],
  },
  {
    id: "leg-raises-floor",
    name: "Relevés de jambes au sol",
    category: "core",
    muscleGroups: ["abdos", "obliques", "iliens"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 10,
    defaultTargetMax: 20,
    defaultRest: 60,
    progression: "Vers relevés suspendus",
    alternatives: ["knee-raises", "leg-raises-hanging"],
  },

  // ── SKILLS AVANCÉS ──
  {
    id: "tuck-flag",
    name: "Tuck flag",
    category: "skill",
    muscleGroups: ["obliques", "abdos", "épaules"],
    equipment: ["pullup-bar", "rings", "bodyweight"],
    difficulty: 3,
    kind: "time",
    defaultSets: 5,
    defaultTargetMin: 5,
    defaultTargetMax: 20,
    defaultRest: 120,
    progression: "Vers advanced tuck, puis full flag",
    alternatives: ["tuck-flag-one-leg", "side-plank"],
  },
  {
    id: "tuck-flag-one-leg",
    name: "Tuck flag une jambe tendue",
    category: "skill",
    muscleGroups: ["obliques", "abdos", "épaules"],
    equipment: ["pullup-bar", "bodyweight"],
    difficulty: 2,
    kind: "time",
    defaultSets: 4,
    defaultTargetMin: 5,
    defaultTargetMax: 15,
    defaultRest: 120,
    progression: "Vers tuck flag",
    alternatives: ["tuck-flag", "side-plank"],
  },
  {
    id: "dragon-flag",
    name: "Dragon flag",
    category: "skill",
    muscleGroups: ["abdos", "épaules", "ischios"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: 3,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 3,
    defaultTargetMax: 8,
    defaultRest: 90,
    progression: "Vers dragon flag jambes fléchies",
    alternatives: ["dragon-flag-bent", "leg-raises-hanging"],
  },
  {
    id: "dragon-flag-bent",
    name: "Dragon flag jambes fléchies",
    category: "skill",
    muscleGroups: ["abdos", "épaules"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 3,
    defaultTargetMax: 6,
    defaultRest: 90,
    progression: "Vers dragon flag full",
    alternatives: ["dragon-flag", "leg-raises-floor"],
  },
  {
    id: "lsit-progression",
    name: "L-sit progression",
    category: "skill",
    muscleGroups: ["abdos", "épaules", "iliens"],
    equipment: ["bodyweight", "pullup-bar", "rings"],
    difficulty: 2,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 5,
    defaultTargetMax: 25,
    defaultRest: 90,
    progression: "Vers L-sit tenu",
    alternatives: ["lsit-tuck", "leg-raises-hanging"],
  },
  {
    id: "lsit-tuck",
    name: "L-sit jambes fléchies (tuck)",
    category: "skill",
    muscleGroups: ["abdos", "épaules", "iliens"],
    equipment: ["bodyweight", "pullup-bar", "rings"],
    difficulty: 1,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 10,
    defaultTargetMax: 30,
    defaultRest: 60,
    progression: "Vers L-sit progression",
    alternatives: ["lsit-progression", "knee-raises"],
  },

  // ── LEGS ──
  {
    id: "squats-bodyweight",
    name: "Squats poids du corps / jump squats",
    category: "legs",
    muscleGroups: ["quadriceps", "ischios", "fessiers", "mollets"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 12,
    defaultTargetMax: 20,
    defaultRest: 90,
    progression: "Vers squats lents (tempo 3-1-3)",
    alternatives: ["squats-slow", "bulgarian-split"],
  },
  {
    id: "squats-slow",
    name: "Squats lents (tempo 3-1-3)",
    category: "legs",
    muscleGroups: ["quadriceps", "ischios", "fessiers"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 8,
    defaultTargetMax: 15,
    defaultRest: 90,
    progression: "Vers squats avec haltères",
    alternatives: ["squats-bodyweight", "bulgarian-split"],
  },
  {
    id: "bulgarian-split",
    name: "Bulgarian split squats",
    category: "legs",
    muscleGroups: ["quadriceps", "ischios", "fessiers"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 8,
    defaultTargetMax: 12,
    defaultRest: 90,
    progression: "Vers fentes marchées",
    alternatives: ["lunges-reverse", "squats-bodyweight"],
  },
  {
    id: "lunges-reverse",
    name: "Fentes arrière",
    category: "legs",
    muscleGroups: ["quadriceps", "ischios", "fessiers"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 10,
    defaultTargetMax: 15,
    defaultRest: 60,
    progression: "Vers Bulgarian split",
    alternatives: ["bulgarian-split", "squats-bodyweight"],
  },
  {
    id: "lunges-walking",
    name: "Fentes marchées ou inversées",
    category: "legs",
    muscleGroups: ["quadriceps", "ischios", "fessiers"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 10,
    defaultTargetMax: 12,
    defaultRest: 90,
    progression: "Vers fentes avec charge",
    alternatives: ["bulgarian-split", "lunges-reverse"],
  },
  {
    id: "pistol-squat",
    name: "Pistol squat progression",
    category: "legs",
    muscleGroups: ["quadriceps", "ischios", "fessiers", "épaules"],
    equipment: ["bodyweight"],
    difficulty: 3,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 3,
    defaultTargetMax: 6,
    defaultRest: 120,
    progression: "Vers pistol squat libre",
    alternatives: ["pistol-box", "squats-bodyweight"],
  },
  {
    id: "pistol-box",
    name: "Pistol squat vers une chaise",
    category: "legs",
    muscleGroups: ["quadriceps", "ischios", "fessiers"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 5,
    defaultTargetMax: 8,
    defaultRest: 90,
    progression: "Vers pistol squat libre",
    alternatives: ["pistol-squat", "squats-bodyweight"],
  },
  {
    id: "hip-thrust",
    name: "Pont fessier / Hip thrusts",
    category: "legs",
    muscleGroups: ["fessiers", "ischios", "abdos"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 12,
    defaultTargetMax: 15,
    defaultRest: 90,
    progression: "Vers hip thrust lesté",
    alternatives: ["hip-thrust-single", "glute-bridge"],
  },
  {
    id: "hip-thrust-single",
    name: "Pont fessier une jambe",
    category: "legs",
    muscleGroups: ["fessiers", "ischios"],
    equipment: ["bodyweight"],
    difficulty: 3,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 8,
    defaultTargetMax: 12,
    defaultRest: 90,
    progression: "Vers hip thrust two-leg",
    alternatives: ["hip-thrust", "glute-bridge"],
  },
  {
    id: "calf-raises",
    name: "Élevés de mollets",
    category: "legs",
    muscleGroups: ["mollets"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 15,
    defaultTargetMax: 25,
    defaultRest: 60,
    progression: "Vers élevés sur marche",
    alternatives: ["calf-raises-step", "jump-rope"],
  },
  {
    id: "calf-raises-step",
    name: "Mollets sur une marche",
    category: "legs",
    muscleGroups: ["mollets"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "reps",
    defaultSets: 4,
    defaultTargetMin: 12,
    defaultTargetMax: 20,
    defaultRest: 60,
    progression: "Vers élevés chargés",
    alternatives: ["calf-raises", "jump-rope"],
  },

  // ── CORE ──
  {
    id: "hollow-body-hold",
    name: "Hollow body hold",
    category: "core",
    muscleGroups: ["abdos", "épaules", "iliens"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 20,
    defaultTargetMax: 45,
    defaultRest: 60,
    progression: "Vers hollow body jambes tendues",
    alternatives: ["hollow-body-bent", "dead-bug"],
  },
  {
    id: "hollow-body-bent",
    name: "Hollow body jambes fléchies",
    category: "core",
    muscleGroups: ["abdos", "épaules"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 20,
    defaultTargetMax: 40,
    defaultRest: 60,
    progression: "Vers hollow body hold",
    alternatives: ["hollow-body-hold", "dead-bug"],
  },
  {
    id: "dead-bug",
    name: "Dead bug",
    category: "core",
    muscleGroups: ["abdos", "épaules"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 8,
    defaultTargetMax: 12,
    defaultRest: 60,
    progression: "Vers hollow body",
    alternatives: ["hollow-body-bent", "hollow-body-hold"],
  },
  {
    id: "plank",
    name: "Planche",
    category: "core",
    muscleGroups: ["abdos", "épaules", "iliens"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 30,
    defaultTargetMax: 60,
    defaultRest: 60,
    progression: "Vers planche latérale lestée",
    alternatives: ["plank-knee", "plank-shoulder-taps"],
  },
  {
    id: "plank-knee",
    name: "Planche sur les genoux",
    category: "core",
    muscleGroups: ["abdos", "épaules"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 30,
    defaultTargetMax: 60,
    defaultRest: 45,
    progression: "Vers planche classique",
    alternatives: ["plank", "dead-bug"],
  },
  {
    id: "plank-shoulder-taps",
    name: "Planche touchés d'épaules",
    category: "core",
    muscleGroups: ["abdos", "épaules"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "reps",
    defaultSets: 3,
    defaultTargetMin: 10,
    defaultTargetMax: 20,
    defaultRest: 45,
    progression: "Vers planche latérale",
    alternatives: ["plank", "plank-knee"],
  },
  {
    id: "side-plank",
    name: "Planche latérale",
    category: "core",
    muscleGroups: ["obliques", "abdos"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 20,
    defaultTargetMax: 45,
    defaultRest: 45,
    progression: "Vers planche latérale lestée",
    alternatives: ["side-plank-knee", "tuck-flag"],
  },
  {
    id: "side-plank-knee",
    name: "Planche latérale genoux",
    category: "core",
    muscleGroups: ["obliques", "abdos"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 20,
    defaultTargetMax: 40,
    defaultRest: 45,
    progression: "Vers planche latérale",
    alternatives: ["side-plank", "tuck-flag"],
  },
  {
    id: "side-plank-weighted",
    name: "Planche latérale lestée",
    category: "core",
    muscleGroups: ["obliques", "abdos"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: 2,
    kind: "time",
    defaultSets: 4,
    defaultTargetMin: 30,
    defaultTargetMax: 55,
    defaultRest: 60,
    progression: "Vers tuck flag",
    alternatives: ["side-plank", "tuck-flag"],
  },
  {
    id: "plank-weighted-combo",
    name: "Planche + planche latérale lestée",
    category: "core",
    muscleGroups: ["abdos", "obliques", "épaules"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: 2,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 30,
    defaultTargetMax: 55,
    defaultRest: 60,
    progression: "Vers planche latérale lestée",
    alternatives: ["plank", "side-plank-weighted"],
  },
  {
    id: "mountain-climbers",
    name: "Mountain climbers",
    category: "core",
    muscleGroups: ["abdos", "épaules", "quadriceps"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 30,
    defaultTargetMax: 45,
    defaultRest: 60,
    progression: "Vers mountain climbers lents",
    alternatives: ["plank-shoulder-taps", "dead-bug"],
  },
  {
    id: "mountain-climbers-slow",
    name: "Mountain climbers lents",
    category: "core",
    muscleGroups: ["abdos", "épaules", "quadriceps"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "time",
    defaultSets: 3,
    defaultTargetMin: 30,
    defaultTargetMax: 45,
    defaultRest: 60,
    progression: "Contrôle qualité avant vitesse",
    alternatives: ["mountain-climbers", "plank"],
  },

  // ── CARDIO ──
  {
    id: "running-zone2",
    name: "Course Zone 2",
    category: "cardio",
    muscleGroups: ["quadriceps", "ischios", "fessiers", "mollets", "cardio"],
    equipment: ["bodyweight"],
    difficulty: 1,
    kind: "distance",
    defaultSets: 1,
    defaultTargetMin: 5,
    defaultTargetMax: 8,
    defaultRest: 0,
    progression: "+1 km toutes les 1-2 semaines",
    alternatives: ["rowing-zone2", "bike-zone2"],
  },
  {
    id: "running-intervals",
    name: "Course fractionné",
    category: "cardio",
    muscleGroups: ["quadriceps", "ischios", "fessiers", "mollets", "cardio"],
    equipment: ["bodyweight"],
    difficulty: 2,
    kind: "distance",
    defaultSets: 1,
    defaultTargetMin: 5,
    defaultTargetMax: 8,
    defaultRest: 0,
    progression: "Augmenter le nombre d'intervalles",
    alternatives: ["rowing-hiit", "bike-hiit"],
  },
  {
    id: "rowing-zone2",
    name: "Rameur Zone 2",
    category: "cardio",
    muscleGroups: ["dos", "épaules", "bras", "cardio"],
    equipment: ["rower"],
    difficulty: 1,
    kind: "time",
    defaultSets: 1,
    defaultTargetMin: 20,
    defaultTargetMax: 40,
    defaultRest: 0,
    progression: "+5 min toutes les 2 semaines",
    alternatives: ["running-zone2", "bike-zone2"],
  },
  {
    id: "rowing-hiit",
    name: "Rameur HIIT",
    category: "cardio",
    muscleGroups: ["dos", "épaules", "bras", "cardio"],
    equipment: ["rower"],
    difficulty: 2,
    kind: "time",
    defaultSets: 1,
    defaultTargetMin: 10,
    defaultTargetMax: 20,
    defaultRest: 0,
    progression: "+1 intervalle toutes les 2 semaines",
    alternatives: ["running-intervals", "bike-hiit"],
  },
  {
    id: "bike-zone2",
    name: "Vélo Zone 2",
    category: "cardio",
    muscleGroups: ["quadriceps", "ischios", "fessiers", "mollets", "cardio"],
    equipment: ["bike"],
    difficulty: 1,
    kind: "time",
    defaultSets: 1,
    defaultTargetMin: 20,
    defaultTargetMax: 40,
    defaultRest: 0,
    progression: "+5 min toutes les 2 semaines",
    alternatives: ["running-zone2", "rowing-zone2"],
  },
  {
    id: "bike-hiit",
    name: "Vélo HIIT",
    category: "cardio",
    muscleGroups: ["quadriceps", "ischios", "fessiers", "mollets", "cardio"],
    equipment: ["bike"],
    difficulty: 2,
    kind: "time",
    defaultSets: 1,
    defaultTargetMin: 10,
    defaultTargetMax: 20,
    defaultRest: 0,
    progression: "+1 intervalle toutes les 2 semaines",
    alternatives: ["running-intervals", "rowing-hiit"],
  },
  {
    id: "pool-crawl",
    name: "Piscine crawl",
    category: "cardio",
    muscleGroups: ["dos", "épaules", "bras", "jambes", "cardio"],
    equipment: ["pool"],
    difficulty: 2,
    kind: "time",
    defaultSets: 1,
    defaultTargetMin: 20,
    defaultTargetMax: 40,
    defaultRest: 0,
    progression: "+5 min toutes les 2 semaines",
    alternatives: ["running-zone2", "rowing-zone2"],
  },
  {
    id: "pool-intervals",
    name: "Piscine intervalles",
    category: "cardio",
    muscleGroups: ["dos", "épaules", "bras", "jambes", "cardio"],
    equipment: ["pool"],
    difficulty: 3,
    kind: "time",
    defaultSets: 1,
    defaultTargetMin: 10,
    defaultTargetMax: 20,
    defaultRest: 0,
    progression: "+1 intervalle toutes les 2 semaines",
    alternatives: ["running-intervals", "rowing-hiit"],
  },
];

/**
 * Regroupe les exercices par catégorie pour un accès rapide.
 */
export const EXERCISES_BY_CATEGORY: Record<ExerciseCategory, ExerciseTemplate[]> = {
  push: EXERCISE_POOL.filter((e) => e.category === "push"),
  pull: EXERCISE_POOL.filter((e) => e.category === "pull"),
  legs: EXERCISE_POOL.filter((e) => e.category === "legs"),
  core: EXERCISE_POOL.filter((e) => e.category === "core"),
  cardio: EXERCISE_POOL.filter((e) => e.category === "cardio"),
  skill: EXERCISE_POOL.filter((e) => e.category === "skill"),
};

/**
 * Mappe les équipements du profil (format texte) vers les tags du pool.
 * Les équipements non reconnus sont ignorés (l'utilisateur garde le bodyweight).
 */
export const EQUIPMENT_MAP: Record<string, EquipmentTag[]> = {
  "Barre traction": ["pullup-bar"],
  Anneaux: ["rings"],
  Haltères: ["dumbbells"],
  Élastiques: ["bands"],
  "Sangle TRX": ["trx"],
  Rameur: ["rower"],
  Piscine: ["pool"],
  Vélo: ["bike"],
  "Vélo route/VTT": ["bike"],
};

/**
 * Convertit la liste d'équipements textuels du profil en tags du pool.
 * "bodyweight" est toujours inclus (poids du corps = toujours disponible).
 */
export function profileEquipmentToTags(equipment: string[]): EquipmentTag[] {
  const tags: EquipmentTag[] = ["bodyweight"];
  for (const eq of equipment) {
    const mapped = EQUIPMENT_MAP[eq];
    if (mapped) tags.push(...mapped);
  }
  return [...new Set(tags)];
}
